version: '3'
services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - frontend
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
